# Generated by Django 5.2.8 on 2025-11-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
